### ISSUE TITLE
Run Based Algorithm

### ISSUE THREAD

**Issue by ansleliu** [prittt/BACCA#1]
Have you been able to successfully replicate the results of the paper : [An Improved Algorithm for Extraction of Exact Boundaries and Boundaries Inclusion Relationship](https://link.springer.com/chapter/10.1007/978-3-642-38768-5_58) ?

**Comment by ansleliu** [comment]
I have successfully replicated the results

**Comment by prittt** [comment]
Dear @ansleliu, 

I didn't know about that paper. If you managed to replicate the code, you can make a pull request to include it on BACCA benchmark. 

Best, 
Federico.
